// Code generated by mockery v2.30.1. DO NOT EDIT.

package notifications

import mock "github.com/stretchr/testify/mock"

// MockBot is an autogenerated mock type for the Bot type
type MockBot struct {
	mock.Mock
}

// SendMSG provides a mock function with given fields: text
func (_m *MockBot) SendMSG(text string) error {
	ret := _m.Called(text)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBot creates a new instance of MockBot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBot(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBot {
	mock := &MockBot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
