// Code generated by mockery v2.30.1. DO NOT EDIT.

package checkout

import (
	context "context"
	model "route256/checkout/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

// AddToCart provides a mock function with given fields: ctx, user, sku, count
func (_m *MockCartRepository) AddToCart(ctx context.Context, user int64, sku uint32, count uint16) error {
	ret := _m.Called(ctx, user, sku, count)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint32, uint16) error); ok {
		r0 = rf(ctx, user, sku, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFromCart provides a mock function with given fields: ctx, user, sku, count
func (_m *MockCartRepository) DeleteFromCart(ctx context.Context, user int64, sku uint32, count uint16) error {
	ret := _m.Called(ctx, user, sku, count)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint32, uint16) error); ok {
		r0 = rf(ctx, user, sku, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserItems provides a mock function with given fields: ctx, user
func (_m *MockCartRepository) GetUserItems(ctx context.Context, user int64) ([]model.Cart, error) {
	ret := _m.Called(ctx, user)

	var r0 []model.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]model.Cart, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []model.Cart); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSkuItemCount provides a mock function with given fields: ctx, user, sku
func (_m *MockCartRepository) GetUserSkuItemCount(ctx context.Context, user int64, sku uint32) (uint16, error) {
	ret := _m.Called(ctx, user, sku)

	var r0 uint16
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint32) (uint16, error)); ok {
		return rf(ctx, user, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint32) uint16); ok {
		r0 = rf(ctx, user, sku)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, uint32) error); ok {
		r1 = rf(ctx, user, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
